# Generated by Django 5.0.1 on 2024-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartibi'),
            preserve_default=False,
        ),
    ]
